### ISSUE TITLE
Empty sub-message doesn't work

### ISSUE THREAD

**Issue by parastream** [jeffijoe/messageformat.net#2]
Great work! I started replacing my brute-force formatting code with your MessageFormatter.Format method. I found one case where I want an empty string in the zero case, so I tried this:

"{nbrAttachments, plural, zero {} one {{nbrAttachmentsFmt} attachment} other {{nbrAttachmentsFmt} attachments}}"

There is a runtime exception for this, but if I replace the {} with { }, it returns a space and doesn't throw.

I want no display if there are no attachments, but the proper plural display for all others. If I simply omit the "zero {}" part, it returns "0 attachments".

**Comment by jeffijoe** [comment]
I'll look into this, thanks for letting me know (but screw you for finding a bug) :smirk:

Exact exception type, please?

**Comment by jeffijoe** [comment]
@parastream 

For reference, you should format your string like this instead for substituting the number:

```
{nbrAttachments, plural, zero {} one {1 attachment} other {# attachments}}
```

**Comment by parastream** [comment]
Here's the entire exception dump:
`System.ArgumentOutOfRangeException: MaxCapacity must be one or greater.
Parameter name: maxCapacity
   at System.Text.StringBuilder..ctor(Int32 capacity, Int32 maxCapacity)
   at Jeffijoe.MessageFormat.MessageFormatter.UnescapeLiterals(StringBuilder sourceBuilder)
   at Jeffijoe.MessageFormat.MessageFormatter.FormatMessage(String pattern, Dictionary``2 args)
   at Jeffijoe.MessageFormat.MessageFormatter.Format(String pattern, Dictionary``2 data)
   at ParastreamIMS.Accounts.EditAccountForm.UpdateUIState() in c:\Projects\company\sw\Parastream BMS\ParastreamIMS\Accounts\EditAccountForm.cs:line 1595
   at ParastreamIMS.Accounts.EditAccountForm.OpenAccount(Account account) in c:\Projects\company\sw\Parastream BMS\ParastreamIMS\Accounts\EditAccountForm.cs:line 1127
   at ParastreamIMS.Accounts.EditAccountForm.accountIdComboBox_SelectedIndexChanged(Object sender, EventArgs e) in c:\Projects\company\sw\Parastream BMS\ParastreamIMS\Accounts\EditAccountForm.cs:line 1750`

I'm nesting my own formatted string (I want it to have comma separators "N0") instead of using #. It seems to be working perfectly. {{nbrAttachmentsFmt} attachments}  might display something like "1,102 attachments" instead of "1102 attachments", assuming you're using the "ToString" method to render the # token. I set the "nbrAttachmentsFmt" entry in the dictionary to the "N0" formatted value.

**Comment by jeffijoe** [comment]
Ah, I see. Will look into this first thing in the morning. Added your case to my test suite. Will let you know. :)

**Comment by parastream** [comment]
Thanks. I didn't expect such a fast response. Leave it to me to find the corner cases :-) Would it make sense to add a property to the class (and/or a constructor overload) to allow for specifying a format string? I tend to do this a lot. Just thinking out loud (I do that a lot, too).

**Comment by parastream** [comment]
Clarification... A format string for rendering the #.

**Comment by jeffijoe** [comment]
A delegate, or just a string? Example please. :)

**Comment by jeffijoe** [comment]
Actually, I think the way you accomplished it is pretty neat and far more customizable than a pretty internal implementation would be.

**Comment by parastream** [comment]
A delegate would be awesome, but probably overkill for my own needs. I was thinking more like an overload `MessageFormatter.Format(pattern, data, format);` (and something similar in the `FormatMessage` method). I'd just set the format argument to "N0".

Regarding the `ctor` suggestion... Upon reflection, adding it to the `ctor` might be confusing; it really belongs in the methods.

**Comment by parastream** [comment]
... not opening this can of worms also works for me :-)

**Comment by jeffijoe** [comment]
Fixed your issue though :) - will publish asap.

**Comment by jeffijoe** [comment]
Boom, committed and published - had a minute to work on it, couldn't wait.

https://github.com/jeffijoe/messageformat.net/commit/67f8f762b59244f56835e547b33d47d0875e9cd7

**Comment by jeffijoe** [comment]
Like I said, I added your case as a test, so it should work. :)
