### ISSUE TITLE
Missing Variable handler

### ISSUE THREAD

**Issue by revenz** [jeffijoe/messageformat.net#20]
Currently any missing variable throws an exception and stops the formatting.

I have a custom "iif" formatter which I have been using in an angular project that I'm converting to blazor and it basically does this
`{SomeVariable, iif, true, false}`
in my iif formatter, i check if its a string, if its not empty, if its a boolean if its true, else its not null etc.

So I request the MessageFormatter expose a "MissingVariableHandler" or a "DontThrowOnMissingVariable".   a function "MissingVariableHandler" could covert that to string.empty or a dontthrow could treat that variable as just null.

**Comment by jeffijoe** [comment]
I suppose each formatter should decide what to do on missing variables.

Sadly I no longer have access to a Windows machine so I need to figure out how I can even ship an update from macOS with code signing first. 😔

**Comment by jeffijoe** [comment]
@revenz I shipped 4.0.0, there is a new `VariableMustExist` getter than you just need to return `false` from in your custom formatter.

Getting all this working on macOS and GitHub actions was interesting. 😄

**Comment by revenz** [comment]
thanks, works pefectly!
