### ISSUE TITLE
Support for IReadOnlyDictionary

### ISSUE THREAD

**Issue by glen-84** [jeffijoe/messageformat.net#29]
```cs
IReadOnlyDictionary<string, object?> dictionary
    = new Dictionary<string, object?>() { { "maximumLength", 100 } }.AsReadOnly();

Console.WriteLine(mf.FormatMessage(
    "Article titles must not contain more than {maximumLength} characters.",
    dictionary));
```

> Unhandled exception. Jeffijoe.MessageFormat.Formatting.VariableNotFoundException: The variable 'maximumLength' was not found in the arguments collection.

**Edit:** It works if you use `ReadOnlyDictionary` (not the interface). We may decide not to use read-only dictionaries (at least via the interface), but it should perhaps be supported anyway?

**Comment by jeffijoe** [comment]
Yeah that’s a bug!
