### ISSUE TITLE
Signed assembly

### ISSUE THREAD

**Issue by Styxxy** [jeffijoe/messageformat.net#3]
Hi,
Would it be possible to sign the assembly so it can easily be used in other signed assemblies?

**Comment by jeffijoe** [comment]
Hi @Styxxy,

I haven't signed an assembly before, but I'll look into it. Would this involve creating a separate NuGet package? Or can others use the signed assembly in unsigned assemblies?

**Comment by jeffijoe** [comment]
@Styxxy 

Would something like [this NuGet package](https://www.nuget.org/packages/Nivot.StrongNaming/) do the job on your end?

**Comment by Styxxy** [comment]
You can use signed assemblies in unsigned assemblies, but not the other way around (build gives an error). Creating a signed asembly is not difficult, just go to the projects properties, the tab "Signing".

I am currently adding some code to an already existing code base (visual studio plugin), so I'd like to minimize the additional code and DLL's as much as possible. Adding a library to sign just one package is a little bit too much overhead (for me).

If it is too much work to sign your assembly, I will fork your repo and sign it myself (but I'd prefer to use the Nuget Package, it is easier to maintain).

**Comment by jeffijoe** [comment]
Will it auto-sign after each release build then?

**Comment by jeffijoe** [comment]
@Styxxy done, and published to NuGet. Thanks for your input.

**Comment by Styxxy** [comment]
Thanks for adding it! :+1:

**Comment by jeffijoe** [comment]
You're welcome! Thanks for using my library. :)
