### ISSUE TITLE
NullRef @ VariableFormatter if any parameter value is null

### ISSUE THREAD

**Issue by erictheswift** [jeffijoe/messageformat.net#4]
This one throws NullRef:

``` csharp
MessageFormatter.Format("{maybeCount}", new {maybeCount = (int?)null});
```

from VariableFormatter.cs#L58

Is VariableFormatter not null-safe by design?
Currently I'm using custom variable formatter as a workaround.

**Comment by jeffijoe** [comment]
I don't think so - what would be the expected output? An empty string or "null"?

**Comment by erictheswift** [comment]
https://github.com/yahoo/intl-messageformat injects nothing as for now
but it also injects nothing instead of 0, so I think that may change :smiley:

**Comment by jeffijoe** [comment]
I'll return an empty string then - gimme a few minutes to push to NuGet.

**Comment by jeffijoe** [comment]
Fixed - see [the integration tests](https://github.com/jeffijoe/messageformat.net/blob/master/src/Jeffijoe.MessageFormat.Tests/MessageFormatter_full_integration_tests.cs#L179-L192).

Thanks for reporting!

**Comment by erictheswift** [comment]
thanks

``` c#
            object value;
            if (!args.TryGetValue(request.Variable, out value))
            {
                return string.Empty;
            }
```

maybe it should `throw VariableNotFoundException` if key was not found in dictionary (as select/plural formatters already seem to do)?

**Comment by jeffijoe** [comment]
Fair point - gimme a few.

**Comment by erictheswift** [comment]
aw, it seems that noone (but test) calls `AssertVariableExists` in BaseFormatter.cs at the moment

**Comment by jeffijoe** [comment]
I just noticed that as well.

**Comment by jeffijoe** [comment]
Maybe it's time to bump to version 1 as this is actually a breaking change despite the fact that it should have been like this from the beginning.

@Metallium what do you think? Throw an exception or just return a default value?

**Comment by erictheswift** [comment]
before that you could receive 'KeyNotFoundException' while getting item from dictionary in VariableFormatter, so I think that does not seem to be a breaking change

I'd rather receive a message that `key` is really missing in my dictionary/dataobject than expect some silenced behavior

**Comment by jeffijoe** [comment]
@Metallium v1 released.
