### ISSUE TITLE
Support for all pluralization rules

### ISSUE THREAD

**Issue by BlueGone** [jeffijoe/messageformat.net#47]
Currently, the PluralFormatter add only a Pluralizer for english. Do you plan on adding other pluralizers by default ?

**Comment by jeffijoe** [comment]
All plural formats should be supported, we have a source generator for it.

**Comment by BlueGone** [comment]
Sorry then. I was debugging the Pluralizer formatter, and found only one PluralRule for "en", but no other, but I did not see that there is a fallback to PluralRulesMetadata.
Thanks.
