### ISSUE TITLE
Problem with the Standard Pluralizer on iPhone

### ISSUE THREAD

**Issue by Falgantil** [jeffijoe/messageformat.net#7]
See AddStandardPluralizers in PluralFormatter. You know what the problem is.

Also see line 151 on PluralFormatter. Same issue

**Comment by jeffijoe** [comment]
Should be fixed in https://github.com/jeffijoe/messageformat.net/commit/4f26470b1cb0d93ec8bd5445432374d5bbd8e531 - published to NuGet as v1.0.2.
