### ISSUE TITLE
Thread safety issues in MessageFormatter.cs

### ISSUE THREAD

**Issue by ramziyassine** [jeffijoe/messageformat.net#9]
### Overview 
I use your library in the realm of internationalization. It is straightforward, and supports the ICU message format. 👍  However I believe there is a threading issue in MessageFormatter mainly around the use of the cache https://github.com/jeffijoe/messageformat.net/blob/master/src/Jeffijoe.MessageFormat/MessageFormatter.cs#L387message that sometimes manifest as the following exceptions 
```
Type=System.ArgumentException
Message=An item with the same key has already been added.
...
Stack Trace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Jeffijoe.MessageFormat.MessageFormatter.ParseRequests(String pattern, StringBuilder sourceBuilder) in d:\Projects\MessageFormat.NET\src\Jeffijoe.MessageFormat\MessageFormatter.cs:line 390
   at Jeffijoe.MessageFormat.MessageFormatter.FormatMessage(String pattern, IDictionary`2 args) in d:\Projects\MessageFormat.NET\src\Jeffijoe.MessageFormat\MessageFormatter.cs:line 230
```

I created a console app and soak test your API (multiple threads re using the same MessageFormatter instance) in hopes to try to reproduce this issue but as many threading problems it was a challenge to get a consistent failure.

### Proposal 
* I know we can use the static method as it has an inherit lock but I was thinking more closely along the line of changing MessageFormatter to use a concurrent dictionary and allow the instances of this class to be shared across threads. I will be more than happy to help create patch and submit a PR if you agree with that mentality

**Comment by jeffijoe** [comment]
Thank you for using my library!

If you can implement it without upgrading the framework version and with all tests passing, by all means go ahead! 😄

**Comment by ramziyassine** [comment]
Do you have a recommended strategy for a PR on this project. and build wise wouldn't we want to upgrade to a minor version? Thank you

**Comment by jeffijoe** [comment]
Yeah go ahead and increment the minor version. Ill publish when I've recovered from surgery. Thanks!

**Comment by ramziyassine** [comment]
Good luck dude and godspeed!!

**Comment by jeffijoe** [comment]
Thanks man, and thanks for helping out!

**Comment by jeffijoe** [comment]
@ramziyassine any updates? Or would you like me to do it? Admittedly it would look better on the contributor stats if you did it. ;)

**Comment by ramziyassine** [comment]
I hope your surgery went ok. I would like to contribute as it is a solid library. I was going to tackle this this week. My one question is, initially I tried import the concurrent dictionary which will require a new dependency, are you ok with that? I feel better using .net's Concurrency then rolling my own using lock access.

**Comment by jeffijoe** [comment]
Is that a nuget package? One of the features of this library is that there are no deps, but if you think it's needed then no problem, we can edit the readme.

My surgery went well, thanks!

**Comment by ramziyassine** [comment]
I am trying to use System.Collections.Concurrent

**Comment by jeffijoe** [comment]
I'm not on my Windows machine right now, and haven't done .NET for a while, is that available in PCL without installing a NuGet package? If so, then go ahead :)

**Comment by ramziyassine** [comment]
👍  I might try this https://www.nuget.org/packages/Portable.ConcurrentDictionary

**Comment by jeffijoe** [comment]
Package has been pushed!
